Update django 51
torchbox/django-pattern-library pull request #251
Opened 2024-10-17 00:40 UTC by mark-meyer

## Description

Please include a summary of the changes and which issue this relates to (if applicable).

Fixes # (issue)
Updates project to support Django 5.1

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] I have added an appropriate CHANGELOG entry

2024-10-17 14:37 UTC, zerolab requested changes
The changes themselves look good.
Made a suggestion to do a bit of tidy up while at it (Drop Django < 4.2, Python < 3.9)

2024-10-17 14:37 UTC, zerolab commented on pyproject.toml
> +Django = ">=3.2,<5.2"
Given 3.2 is no longer supported

```suggestion
Django = ">=4.2,<5.2"
```

Also, it would be good to drop Python 3.8 and add 3.12 to the matrix

2024-10-17 15:13 UTC, mark-meyer commented
Thanks @zerolab — I've added this change. I'm not sure where you mean to drop Python 3.8 — I *think* Django 4.2 still supports Py3.8. 

I did drop Django3.2 from the tox dependencies.

2024-10-17 15:19 UTC, zerolab commented
While Django 4.2 still supports it, Python 3.8 is no longer maintained - https://endoflife.date/python - so this is a good time to drop it

2024-10-17 15:28 UTC, zerolab reviewed
a few more suggestions

2024-10-17 15:28 UTC, zerolab commented on pyproject.toml
> +    "Framework :: Django :: 5.1",
Can you also remove

```
"Framework :: Django :: 3.2",
"Framework :: Django :: 4.1",
```

and add `"Programming Language :: Python :: 3.12",`

2024-10-17 15:28 UTC, zerolab commented on pyproject.toml
>  python = "^3.8"
```suggestion
python = "^3.9"
```
and remove `"Programming Language :: Python :: 3.8",`

2024-10-17 15:28 UTC, zerolab commented on tox.ini
>      py{38,39,310,311,312}-dj42
```suggestion
    py{39,310,311,312}-dj42
```

2024-10-17 15:44 UTC, mark-meyer commented
Thanks @zerolab - I also cleaned up some of the GitHub workflow to remove references to the removed toxenvs and updated the docs.

2024-10-17 16:16 UTC, zerolab commented on docs/getting-started.md
> +- Python 3.9, 3.10, 3.11 (experimental)
```suggestion
- Python 3.9, 3.10, 3.11, 3.12
```

2024-10-17 16:17 UTC, zerolab commented on pyproject.toml
> +    "Programming Language :: Python :: 3.12",
`"Programming Language :: Python :: 3.8",` is still here

2024-10-17 16:18 UTC, zerolab commented
Thank you @mark-meyer. a couple of more things then this is good to go 🙌🏼

2024-10-17 16:28 UTC, zerolab approved these changes
LGTM.
Will leave the tests to run. Hopefully we can make a new release tomorrow (as it is end of the day for me, at least)

2024-10-18 16:26 UTC, merged

2024-11-12 14:31 UTC, zerolab commented
Unfortunately I do not have the power to make a release.

cc @thibaudcolas

2024-11-19 09:11 UTC, dylan8902 commented
@thibaudcolas Would you able to make a release?

2024-11-28 10:01 UTC, chinmay-fincent commented
Hey @thibaudcolas and @zerolab, when will it be released?

2024-12-11 11:53 UTC, thibaudcolas commented
Oh sorry all, we discussed this internally but I didn’t realise so many people were waiting on it. I’ll get on with the release today.

@zerolab as far as I can see you, me, @alxbridge all have release permissions? Let’s check some time (and set up Trusted Publishing).

2024-12-11 21:12 UTC, thibaudcolas commented
…aaand we’re live! [v1.3.0](https://github.com/torchbox/django-pattern-library/releases/tag/v1.3.0) is now out. All working great as far as I can tell :)